# Generated by Django 6.0 on 2025-12-28 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom et prénom de la personne', max_length=200, verbose_name='Nom complet')),
                ('email', models.EmailField(help_text='Email de contact pour la réponse', max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Adresse email')),
                ('message', models.TextField(help_text='Contenu du message envoyé', verbose_name='Message')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date et heure de réception du message', verbose_name='Date de réception')),
                ('lu', models.BooleanField(default=False, help_text="Indique si le message a été lu par l'administrateur", verbose_name='Message lu')),
                ('traite', models.BooleanField(default=False, help_text='Indique si le message a été traité/répondu', verbose_name='Message traité')),
                ('notes', models.TextField(blank=True, help_text="Notes pour l'équipe administrative", null=True, verbose_name='Notes internes')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='core_contac_date_d7567c_idx'), models.Index(fields=['lu'], name='core_contac_lu_03ada9_idx')],
            },
        ),
    ]
