# Generated by Django 6.0 on 2025-12-31 14:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Titre descriptif de l'image", max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, help_text="Description détaillée de l'image", verbose_name='Description')),
                ('image', models.ImageField(help_text='Image de la galerie (JPG, PNG)', upload_to='gallery/%Y/%m/', verbose_name='Image')),
                ('cycle', models.CharField(choices=[('prescolaire', 'Préscolaire'), ('elementaire', 'Élémentaire'), ('secondaire', 'Secondaire'), ('general', 'Général'), ('evenement', 'Événement'), ('infrastructure', 'Infrastructure')], default='general', help_text="Catégorie de l'image", max_length=50, verbose_name='Catégorie')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, help_text="Date d'ajout de l'image", verbose_name="Date d'ajout")),
                ('is_featured', models.BooleanField(default=False, help_text='Afficher cette image en priorité', verbose_name='Image mise en avant')),
                ('is_active', models.BooleanField(default=True, help_text='Afficher cette image dans la galerie', verbose_name='Active')),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage (plus petit = en premier)", verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Image de galerie',
                'verbose_name_plural': 'Images de galerie',
                'ordering': ['order', '-date_uploaded'],
                'indexes': [models.Index(fields=['cycle', '-date_uploaded'], name='core_galler_cycle_7abe3f_idx'), models.Index(fields=['is_active', 'is_featured'], name='core_galler_is_acti_1ace3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Titre de l'article", max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, help_text="URL de l'article (généré automatiquement)", max_length=250, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(help_text="Résumé court de l'article (300 caractères max)", max_length=300, verbose_name='Résumé')),
                ('content', models.TextField(help_text="Contenu complet de l'article", verbose_name='Contenu')),
                ('image', models.ImageField(blank=True, help_text="Image d'illustration de l'article", null=True, upload_to='news/%Y/%m/', verbose_name='Image principale')),
                ('category', models.CharField(choices=[('annonce', 'Annonce'), ('evenement', 'Événement'), ('reussite', 'Réussite'), ('activite', 'Activité'), ('information', 'Information')], default='information', help_text="Catégorie de l'article", max_length=50, verbose_name='Catégorie')),
                ('author', models.CharField(default='Administration EMD', help_text="Auteur de l'article", max_length=100, verbose_name='Auteur')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date et heure de publication', verbose_name='Date de publication')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_published', models.BooleanField(default=True, help_text='Afficher cet article sur le site', verbose_name='Publié')),
                ('is_featured', models.BooleanField(default=False, help_text='Afficher cet article en priorité', verbose_name='Article mis en avant')),
                ('views_count', models.IntegerField(default=0, help_text="Nombre de fois que l'article a été consulté", verbose_name='Nombre de vues')),
            ],
            options={
                'verbose_name': "Article d'actualité",
                'verbose_name_plural': "Articles d'actualité",
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['-published_date'], name='core_newsar_publish_75a99c_idx'), models.Index(fields=['is_published', 'is_featured'], name='core_newsar_is_publ_ac7142_idx'), models.Index(fields=['category'], name='core_newsar_categor_82c61f_idx')],
            },
        ),
    ]
