# Generated by Django 6.0 on 2026-08-29 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_galleryimage_newsarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text="Image supplémentaire de l'article", upload_to='news/%Y/%m/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, help_text="Légende facultative de l'image", max_length=255, verbose_name='Légende')),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage (plus petit = en premier)", verbose_name="Ordre d'affichage")),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='core.newsarticle', verbose_name='Article')),
            ],
            options={
                'verbose_name': "Image d'article",
                'verbose_name_plural': "Images d'articles",
                'ordering': ['order', 'id'],
            },
        ),
    ]
