# Generated by Django 6.0 on 2026-08-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(help_text="URL d'abonnement renvoyée par le service push du navigateur", max_length=500, unique=True, verbose_name='Endpoint')),
                ('p256dh', models.CharField(help_text='Clé publique de chiffrement renvoyée par le navigateur', max_length=255, verbose_name='Clé p256dh')),
                ('auth', models.CharField(help_text="Secret d'authentification renvoyé par le navigateur", max_length=255, verbose_name='Clé auth')),
                ('user_agent', models.CharField(blank=True, default='', help_text="User-Agent du navigateur au moment de l'abonnement", max_length=255, verbose_name='Navigateur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'abonnement")),
                ('last_error', models.CharField(blank=True, default='', help_text="Dernière erreur d'envoi (utile pour repérer les abonnements expirés)", max_length=255, verbose_name='Dernière erreur')),
            ],
            options={
                'verbose_name': 'Abonnement push',
                'verbose_name_plural': 'Abonnements push',
                'ordering': ['-created_at'],
            },
        ),
    ]
